name: Run Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.16.3
      uses: actions/setup-node@v1
      with:
        node-version: 12.16.3
    - run: npm install
    - run: npm test
